### PR TITLE
Moved change from branch amd_fix to this branch

### PR DESCRIPTION
**Pull request by sweetlikepete**
Old branch was amd_fix_without_code_style_changes. This branch contains the change without any of the code styling changes.

### CODE REVIEW

**Comment by wlindemann** [comment]
@sweetlikepete I left a note in Asana, but if you can work on testing this - we don't have anyone here who is ready to go on that.

**Comment by sweetlikepete** [comment]
No problem. My understanding is that the library should load and function correctly through requirejs.

I've only read about it - haven't used requirejs before in production. I know the pattern from using nodejs. Will set it up and test that it works correctly in browser.

**Comment by dmitrig01** [comment]
requirejs == AMD == using define() functions == loading code async

commonjs == using require() functions == loading code synchronously == what node uses and what browserify uses

**Comment by dmitrig01** [comment]
umd (what we have in the web sdk) is a wrapper that supports both

**Comment by dmitrig01** [comment]
(ideally)

**Comment by jsaleigh** [comment]
:+1:

**Pull request merged**
