### PR TITLE
send browser finegrprint on every request

### PR DESCRIPTION
**Pull request by dmitrig01**
@Kirkkt

### CODE REVIEW

**Comment by Kirkkt** [comment]
test/test.html seems broken, can you double-check?

**Comment by dmitrig01** [comment]
it thorws some errors for me, but they don't seem to be related - i see errors with the history pushstate - but i get those on master too

**Comment by Kirkkt** [comment]
all tests passed on the latest master branch for me

for starters, can you doublecheck whether you need to update this test https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/send-browser-fingerprint-id/test/6_branch.js#L400 ?

**Comment by dmitrig01** [comment]
weird - those are not failing on me, but they definitely would need to be changed. hmm, something is definitely fishy here

**Comment by dmitrig01** [comment]
fixed

**Comment by Kirkkt** [comment]
:+1:
sick

**Pull request merged**
