### PR TITLE
rename src/ and test/ files to honor deps

### PR DESCRIPTION
**Pull request by Kirkkt**
@dmitrig01 
This PR is **not merge-ready**.

But I'd like to give you a quick preview. Let me know if this is something reasonable :)

### CODE REVIEW

**Comment by Kirkkt** [comment]
Background: our file naming system is great. To make it follow the actual deps closely, I renamed a bunch of files so that 0_abc.js is guaranteed to not depend on 0_def.js and 1_ghi.js and so on and so forth.

**Comment by Kirkkt** [comment]
@jakecadams  as well since this could be a substantial change.

**Comment by dmitrig01** [comment]
cool, i like it

**Comment by dmitrig01** [comment]
i think in terms of actual impact it's probably quite small really

**Comment by Kirkkt** [comment]
fyi: I'd like to merge this after the release of v1.6.11 for consistency reasons.

the next release is gonna be a lot of fun for us :)

**Pull request merged**
