### PR TITLE
Rip out cordova

### PR DESCRIPTION
**Pull request by scotthasbrouck**
not ready yet...

### CODE REVIEW

**Comment by scotthasbrouck** [comment]
@dmitrig01 this rips out Cordova and Titanium

**Comment by dmitrig01** [comment]
:+1:

**Comment by scotthasbrouck** [comment]
fyi, the new fixes to sauce are on the has_app branch

**Comment by Deminetix** [comment]
Wait, what? This just broke our app builds... where is the new repo located?

**Comment by aaustin** [comment]
@Deminetix sorry about this - way too many people were confused about this jumbled up integration. Can you point to this repo now?
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK

**Pull request merged**
