### PR TITLE
Revert "re-make integration-test.html to test against min.js"

### PR DESCRIPTION
**Pull request by Kirkkt**
Reverts BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#158

### CODE REVIEW

**Comment by Kirkkt** [comment]
@dmitrig01

**Comment by Kirkkt** [comment]
for future reference, for both of us, let's only merge green PRs :)

**Comment by dmitrig01** [comment]
heh sorry - it's hard to tell if it's actually red or just sauce is stupid

**Comment by Kirkkt** [comment]
NP!
The blame goes to me 99%.

**Pull request merged**
