### PR TITLE
Banner stars fix

### PR DESCRIPTION
**Pull request by jsaleigh**

### CODE REVIEW

**Comment by jeanmw** [comment]
hey @jsaleigh not sure why these circleci checks still keep failing :( let me know if you know what I need to do

**Comment by jsaleigh** [comment]
@jeanmw there's something going on with Sauce Labs, i need to dig in and figure it out

**Comment by jsaleigh** [comment]
Besides the tests, the code looks good.  We especially need those tests for this particular PR though, so I have to wait to merge it.

**Comment by jeanmw** [comment]
@jsaleigh no worries thanks for checking it out - let me know if I can help

**Comment by jsaleigh** [comment]
@jeanmw I manually ran the tests, it all looks good. We just need device testing now.  Merging to master.

**Pull request merged**
