### PR TITLE
include options to remove -e backup files in release.sh

### PR DESCRIPTION
**Pull request by Kirkkt**
@dmitrig01

### CODE REVIEW

**Comment by dmitrig01** [comment]
let's rm -f so if they don't exist for wahtever reason, it doesn't fail

**Comment by dmitrig01** [comment]
you can also rm multiple things in one statmeent :-)

```
rm -f bower.json-e  CHANGELOG.md-e package.json-e plugin.xml-e src/0_config.js-e test/web-config.js-e
```

**Comment by Kirkkt** [comment]
ha, I learned something new :)

**Comment by Kirkkt** [comment]
both done!

**Pull request merged**
