### PR TITLE
use === through and through

### PR DESCRIPTION
**Pull request by Kirkkt**

### CODE REVIEW

**Comment by dmitrig01** [comment]
:+1:

**Comment by dmitrig01** [comment]
but you sholdn't be merging things without someone else approving :P

**Comment by Kirkkt** [comment]
Thought of these as trivial (i.e. these are all string-to-string, number-to-number comparisons).

Should I get approved for all PRs, or just the ones that actually has business logic impact?

**Comment by dmitrig01** [comment]
personally i'm in favor of getting a second pair of eyes on eevrything

**Comment by Kirkkt** [comment]
noted!

**Comment by dmitrig01** [comment]
thanks!

**Pull request merged**
