### PR TITLE
use deepview for banner in all scenarios, even if there is a referring link

### PR DESCRIPTION
**Pull request by dmitrig01**
@jsaleigh 

deepview includes handling for referring link, we should definitely not be putting it behind the banner button, otherwise it'll just redirect to the page you're already on

### CODE REVIEW

**Comment by jsaleigh** [comment]
Makes sense :+1:

**Comment by jsaleigh** [comment]
@dmitrig01 the conflicts look like just build files, let me know if you would like me to fix that and merge

**Comment by dmitrig01** [comment]
yes please!!

**Comment by dmitrig01** [comment]
let's add a changelog entry too - how about "fixes banner call to use deepview logic even if there is a referring link"

**Pull request merged**
