### PR TITLE
[SIMPLE] this console.log doesn't seem to do anything

### PR DESCRIPTION
**Pull request by Kirkkt**
also inlined a var since... why bother?

@dmitrig01

### CODE REVIEW

**Comment by dmitrig01** [comment]
I would prefer to keep constants separate from code - but perhap we should change it to COOKIE_MS or something?

**Comment by dmitrig01** [comment]
that way we don't have any 'magic numbers', but instead they are labelled

**Comment by Kirkkt** [comment]
cool idea!

**Comment by Kirkkt** [comment]
Done :)

@dmitrig01

**Pull request merged**
